library(ggplot2)
library(cowplot)

#################################
# SETTINGS

# Specify the subject area title that will be used to label your graphs
subject_title <- "Golf Architecture"

# Enter around 5-10 accounts that are representative of the golf industry in general for the segments
# you want to target
accounts_of_interest <- c(
  #  "OCCMGolf",
  #  "LOBBandPARTNERS",
  "Hainesy76",
  #  "DeVriesDesigns",
  #  "gcamagazine",
  #  "JasonWay1493",
  #  "GolfDesignNews",
  #  "coorecrenshaw",
  #  "RTJ2GolfDesign",
  #  "DavidMcLayKidd",
  #  "BobHarrisonGolf",
  #  "EdwinRoald",
  #  "MichaelClayto15",
  #  "Planet_Golf",
  #  "KylePhillipsGCD",
  "LinksGems"
  #  "the_fried_egg"
)

# Enter another 5-10 accounts that are much narrower in focus on the sub-segment of the
# golf industry that you want to target. e.g. turf grass associations, or golf managers etc...
narrower_accounts_of_interest <- c(
  "TheSAGCA",
  "ASGCA",
  "EIGCA"
  # "GCSAA",
  # "AGCSA2"
)

# Enter how many followers you are intending to retrieve from the above mentioned accounts
# note that you might want to start with a pretty small number to test with then for your
# big run then ramp it up to 10s of thousands
max_sample_size <- 20000 # 20000

# The max number of tweets to retrieve for each of the accounts we're querying
max_tweet_count <- 3000 # 3000

# The start and end date for our analysis
start_date <- "2017-01-01"
end_date <- "2017-12-31"

# Inactivity cutoff - any target accounts with less than this number of status updates
# won't be considered (you should consider this relative to the date range given above
# try to work out a reasonable number of tweets within that date range)
min_status_updates <- 50

# Max number of friends before we treat the account as a bot
max_friend_count <- 1e4 # 10,000

# Account names to explicitly exclude
accounts_to_exclude <- c(
  "NoLayingUp",
  "TronCarterNLU",
  "DJPie",
  "chambleebrandel",
  "PGATOUR",
  "IanJamesPoulter",
  "JustinRose99",
  "EuropeanTour",
  "JasonSobelESPN",
  "TheSergioGarcia",
  "TheOpen",
  "themichellewie",
  "bubbawatson",
  "shanebacon",
  "LukeDonald",
  "NickFaldo006",
  "BillyHo_Golf",
  "RickieFowler",
  "usopengolf",
  "KellyTilghmanGC",
  "JustinRayGC",
  "TheSandraGal",
  "Adam_Sarson",
  "Fehertwit",
  "Amanda_Balionis",
  "plarrazabal",
  "bowdo83",
  "danjenkinsgd",
  "Fooch1993",
  "AshleyKMayo",
  "TheChristinaKim",
  "RCabreraBello",
  "TheHomeofGolf",
  "AlanShipnuck",
  "ANNIKA59",
  "McIlroyRory",
  "suzannpettersen",
  "PGATOURSMartin",
  "GolfWRX",
  "HarryArnettCG",
  "JordanSpieth",
  "peterjkostis",
  "dougferguson405",
  "ronsirak",
  "StephanieWei",
  "goodwalkspoiled",
  "beemerpga",
  "RichLernerGC",
  "CH3golf",
  "ErinHillsGolf",
  "GCMorningDrive",
  "Keegan_Bradley",
  "WalkerCup",
  "cabotlinks",
  "johnmaginnes",
  "ArronOberholser",
  "IBFinchy",
  "KyleHegland3",
  "Chris_Kirk_",
  "GolfBible",
  "b_dechambeau",
  "patgossnugolf",
  "FrankNobiloGC",
  "BidGreenJacket",
  "Luke_Elvy",
  "BeatrizRecari",
  "BigRandyNLU",
  "ghostofhogan",
  "johnhuggan",
  "RoyalDornochGC",
  "GlobalGolfPost",
  "GolfWorld1",
  "Ballyneal",
  "GAofPhilly",
  "usopengolf",
  "PGA",
  "LETgolf",
  "garyplayer",
  "WarrenSmithFOX",
  "WilsonGolf",
  "TheGolfCanada",
  "PinehurstResort",
  "MarkAllenSEN",
  "SeanCovich",
  "MajorDanRooney",
  "KPMGWomensPGA",
  "Oliver_Wilson",
  "rog_royers",
  "DundonaldLinks",
  "TheTodaysGolfer",
  "Flagstick",
  "LeggoGolf",
  "ballyliffin",
  "jwerner05",
  "HolstonHillsCC",
  "Sand_Valley",
  "OldCourseHotel",
  "rydercup",
  "SweetensCove",
  "wpga",
  "IMGgolf",
  "GCSAA",
  "CGCGreenkeeper",
  "ct_turf",
  "PenderSuper",
  "Dudefester2",
  "theturfyoda",
  "TurfEnto",
  "scotdey",
  "paul_armour",
  "tcturf",
  "OakmontHooks",
  "mattgourlaycgcs",
  "iTweetTurf",
  "DarrenJDavisGCS",
  "bob_ranum",
  "kevinsunderman",
  "JaredKalina",
  "IanKinley",
  "gasoutherngcm",
  "ccdetroitGCS",
  "sbrittonturf",
  "Calsuper",
  "westlancsgreens",
  "ToroGolf",
  "GraemeBeatt",
  "GJRobertsTurf",
  "dhardmanturf",
  "tacomaturf",
  "MPowell_DCPC",
  "tomofreemo",
  "gord_mckie",
  "GKdavid_s",
  "GCSAA_NW",
  "GCM_Magazine",
  "JacobsenTurf",
  "CJBents",
  "CM_HGC",
  "EastlakeGCsuper",
  "GHGCGreens",
  "thelakessuper",
  "TKCarolinasGCSA",
  "golf_water",
  "greenkeepingire",
  "TPCPotomacAGR",
  "CordilleraGCM",
  "SuperintndtMag",
  "SuperProblems",
  "SyngentaTurf",
  "TurfgrassC",
  "AndrewTurfNerd",
  "WomenandGolfMag",
  "MarquetteGolf",
  "KateLifke",
  "SeanAHoolehan",
  "RuckusRod22",
  "Harrimanscash",
  "BIGTurfTeaching",
  "CarterHindes",
  "SfurlongScott",
  "andyohaver",
  "JasnaPolanaAGR",
  "pgasofeurope",
  "BlinderBunker",
  "Gazzer27Marsh",
  "MossyOakGolf",
  "dooksgolfclub",
  "GolfChannelPR",
  "MikeFidanza",
  "RobSandilands",
  "jamestlindsay",
  "brianjlaurent",
  "markpherrmann",
  "TheSavageMitch",
  "mdvessely",
  "Golfnl",
  "LuLuCountryClub",
  "nhccsuper",
  "nicholasfolk",
  "scc1897",
  "EllingYelling",
  "dillonmays_",
  "PaceBarry",
  "David61mg",
  "wearegolf",
  "travisolson86",
  "GAPGolfer",
  "JDGolfGuy",
  "golfweekron",
  "Buckeyesturf",
  "Clanky23",
  "ScottASchurman",
  "golfgirl",
  "jeffreydmorgan",
  "dunbargolfclub",
  "TheBrianEvenson",
  "NathanGlaser",
  "3sticksCGCS",
  "Royal_JHB_Golf",
  "tullfescue",
  "jaywad13",
  "huey_mike",
  "nextgolfer",
  "lovett_benjamin",
  "GriffithsJayson",
  "vgolfman",
  "MPoundSTI",
  "GolfRecruiter",
  "shanewrightcgcs",
  "striturf_adamn",
  "TedFist1",
  "OhioTurfgrass",
  "jeffdstauffer",
  "tptourgolf",
  "GbrSportingClub",
  "RichardSorrell3",
  "turfwheels",
  "stannesgreens",
  "SodSolutions",
  "mcphersoncomm",
  "bbrowningfert",
  "VisitFifeGolf",
  "LSCsuper",
  "CampeyTurfCare",
  "matthewcorentin",
  "CaseyOld",
  "Will_Harrell",
  "MyGolfWay",
  "countyturf",
  "mowlikeachamp",
  "MiGCSA",
  "manfescue",
  "PCC1854Grounds",
  "AussieGolfer",
  "RCC_Grounds",
  "jonsjennings",
  "MidlandTurf",
  "ECabreraBello",
  "stenodocgolf",
  "GaryVanSickle",
  "EffTruck",
  "streamsong",
  "vogeygolf",
  "bamabearcat",
  "golfbreaks",
  "Pooshdaddy",
  "TheGolfClub",
  "GolfUnited",
  "thegolfscape",
  "RainBirdCorp",
  "SteveThePunter",
  "TurfBusiness",
  "golf_inmorocco",
  "TheAPosition",
  "seshnarchitect",
  "PGAmag",
  "FitGolfPGH",
  "GolfTravel4U",
  "BillFields1",
  "cbgolfchallenge",
  "GolfTrips",
  "ScottMichaux",
  "eddiebgolf",
  "worplesdongolf",
  "turfpath",
  "mikebelindo",
  "jpnewport",
  "Offtheteejr",
  "theshirelondon",
  "FMCturf",
  "golfindustria",
  "wsmgolfclub",
  "groundsmaiden",
  "Pblatshaw",
  "phattimer",
  "tombedell",
  "NorthBerwickGol",
  "Aquatrols",
  "AngusFraserMktg",
  "MoortownGC",
  "HOGGOLFBLOG",
  "GolfingLinksOrg",
  "Wholeinonegolf",
  "seanmrivers",
  "PerryGolf",
  "broadstonegc",
  "CMAEurope",
  "istyleuk",
  "lesroches_en",
  "marielufer",
  "schunntu",
  "GolfClubSec",
  "GolfDrivingBays",
  "MattRMBlake",
  "joshkerns38",
  "chipgolfclub",
  "LindsCollumbell",
  "adamstalgolf",
  "SauntonGolfClub",
  "Buffalo_Agency",
  "GetawaysGolf",
  "Coltmm",
  "GEOTurfConsult",
  "BarenbrugUK",
  "cskirchner",
  "EricStrzepek",
  "AtalayaGolf",
  "GMSGolf",
  "montybr",
  "ctmascaro",
  "peaseygolfpro",
  "Official_SFGC",
  "GolfAustMag",
  "mbgolfmarketing",
  "ReesinkTurfcare",
  "POGOTurfPro",
  "Peterlowery",
  "AudubonIntl",
  "HuxleyGolf",
  "PasatiempoGolf",
  "caleBIGelow",
  "SS_Eastern",
  "UGATurfgrass",
  "virgiltourspin",
  "EDSGolf",
  "joeyfr60",
  "ParkinTour",
  "VitaliyKolos",
  "TreetopsMich",
  "BCorcoran7",
  "KeelingGolf",
  "garonparkgolf",
  "novo_gcs",
  "cpgcgreens",
  "FreddyValenti",
  "golfelprat",
  "MiguelMelais",
  "ScotGolfShow",
  "forestdunesgolf",
  "aston_ward",
  "Breiti",
  "tregolfhistoric",
  "pwarms",
  "cradocgc",
  "stevemona1",
  "indigrowuk",
  "SoilSolutions",
  "GolfgiftsScot",
  "RCGLasBrisas",
  "poodlegolf",
  "SusieJFarley",
  "Chronogolf",
  "MJAbbottLtd",
  "socalgolfblog",
  "wissportsaddict",
  "Reyes_golf",
  "ReadingGC",
  "wallygresham",
  "bcarney68",
  "ShootersHillGC",
  "civictrees",
  "playlinksgolf",
  "Christo31809307",
  "Landmark_Golf",
  "waynesheffield",
  "RheinThomas",
  "_Balata_",
  "gordongolf",
  "Mike_GreenCast",
  "GabrielAluisy",
  "Golf_industry",
  "TheGrassGroup",
  "YORKSHIREGOLFER",
  "jmarquez66",
  "BerkhamstedGolf",
  "jtfstewart",
  "FlagHiApp",
  "golfgreek",
  "GCMAUK",
  "irishsportsurf",
  "ISCAudubon",
  "UsEstimating",
  "cestino_jacobo",
  "pgoldiez",
  "Golf_JennyLi",
  "LutonHooGolf",
  "InnerGeniusGolf",
  "Golfbybryan",
  "OUTPOSTCLUB",
  "MattMcLeanGolf",
  "martijnpaehlig",
  "indervanweerelt",
  "Tweston31",
  "BocaWestCC",
  "A1GOLFGB",
  "MetroGolfMags",
  "AndersonWolfUK",
  "GolfProZone",
  "GolfRepro",
  "CapConGolf",
  "Turf_Dynamics",
  "si_stevenson",
  "bonniedoongc",
  "OSWGR",
  "capewickham",
  "GBNPublisher",
  "meadow1927",
  "GilCapps",
  "CJ_Bertram",
  "RainBirdGolf",
  "RussMayneGolf",
  "KeithHaslam",
  "iGolfReviews",
  "JCBgolfCM",
  "DAVIDBATALLER",
  "BostonGolfClub",
  "JamieSlonis",
  "mccallenbmc",
  "CanalShores",
  "Golf_AtlntcIrr",
  "GlobalGolfAdvis",
  "EvergreenTurfAZ",
  "brianmooreturf",
  "Chatham_Hills",
  "GriffinGateLex",
  "Barenbrug_AW",
  "barrygeorgeturf",
  "PittsGeorge",
  "ET_Destinations",
  "GaryCompton",
  "ArangurenInaki"
)

# END SETTINGS
#################################


h_index <- function(x) {
  y <- 1:nrow(x)
  step1 <- x >= y
  step2 <- max(which(step1 == T))
  return(step2)
}

remove_accounts <- function(x, accounts_to_remove){
  # this assumes the data frame passed in has a column called "screen_name"
  x$screen_name_tolower <- tolower(x$screen_name)
  return(x[!x$screen_name_tolower %in% tolower(accounts_to_remove), ])
}

