# ASSUMPTIONS
# data_timelines is present in the global environment, generated by data_get.R. Or load them from file e.g.:
# load("data_accounts2.RData", .GlobalEnv)
# load("data_timelines2.RData", .GlobalEnv)
# also this file assumes it has been invoked from init where it's settings and h_index function are defined

# Some more tidyups
# data_timelines <- subset(data_timelines, is_retweet == FALSE)

# Re-apply the minimum tweet count (previously we did it to the accounts list, now the timeline)
# data_timelines$tweet_count <- ave(data_timelines$is_retweet, data_timelines$screen_name, FUN = length)
# data_timelines <- data_timelines[with(data_timelines, tweet_count >= 50), ]

# order the file by screen_name and favorite count descending
data_timelines_orderby_favorites <- data_timelines[with(data_timelines, order(screen_name, -favorite_count)), ]

# remove tweets that didn't get any favorites (it should have no impact on the h-index)
data_timelines_orderby_favorites <- subset(data_timelines_orderby_favorites, favorite_count > 0)

# I expect that I can slice this up by screen_name, 
# then output to a new file of screen_name + h-index

# refactor the screen names and number them for easy subsetting
data_timelines_orderby_favorites$screen_name_factored <- factor(data_timelines_orderby_favorites$screen_name)
data_timelines_orderby_favorites$account_integer <- as.numeric(data_timelines_orderby_favorites$screen_name_factored)

# create a data frame to hold the output
favorites <- data.frame()

num_accounts <- max(data_timelines_orderby_favorites$account_integer)

for (i in 1:num_accounts) {
  # get the subset of tweets for this account
  account <- subset(data_timelines_orderby_favorites, account_integer == i)
  
  # store the account's screen name for later
  screen_name <- as.character(account[1, "screen_name"])
  
  # get the vector of favorites for the current account
  favorite_counts <- account["favorite_count"]

  # calculate the h_index  
  h_index_favorites <- h_index(favorite_counts)

  # tack it onto the favorites data frame  
  newline <- cbind.data.frame(screen_name, h_index_favorites)
  favorites <- rbind.data.frame(favorites, newline)
}

# match the screen_names in order of the h_index_favorites
favorites$screen_name <- reorder(favorites$screen_name, favorites$h_index_favorites)

# order this, then select top 50
favorites_orderby_hindex <- favorites[with(favorites, order(-h_index_favorites)), ]

forPlot <- favorites_orderby_hindex[1:50, ]

p <- ggplot(data = forPlot, aes(x = h_index_favorites, y = screen_name))
p +
  theme_cowplot(font_family = "Avenir Next") +
  background_grid(major = "xy") +
  geom_point(shape = 0) +
  labs(x = "h-index (based on likes)",
       y = "Twitter Username",
       caption = "h-index: number of tweets (n) with at least (n) likes\ne.g. an h-index of 50 means that account had 50 tweets\nthat were liked 50 or more times (higher is better)",
       title = paste("50 Most Liked Twitter Accounts in", subject_title),
       subtitle = "Compiled by Adrian Logue (@AdrianLogue)"
  )
