# ASSUMPTIONS
# data_timelines is present in the global environment, generated by data_get.R. Or load them from file e.g.:
# load("data_accounts2.RData", .GlobalEnv)
# load("data_timelines2.RData", .GlobalEnv)
# also this file assumes it has been invoked from init where it's settings and h_index function are defined

# Some more tidyups
# data_timelines <- subset(data_timelines, is_retweet == FALSE)

# Re-apply the minimum tweet count (previously we did it to the accounts list, now the timeline)
# data_timelines$tweet_count <- ave(data_timelines$is_retweet, data_timelines$screen_name, FUN = length)
# data_timelines <- data_timelines[with(data_timelines, tweet_count >= 50), ]

# order the file by screen_name and favorite count descending
data_orderby_likes <- data_timelines_working[with(data_timelines_working, order(screen_name, -favorite_count)), ]

# remove tweets that didn't get any likes (it should have no impact on the h-index)
data_orderby_likes <- subset(data_orderby_likes, favorite_count > 0)

# I expect that I can slice this up by screen_name, 
# then output to a new file of screen_name + h-index

# refactor the screen names and number them for easy subsetting
data_orderby_likes$screen_name_factored <- factor(data_orderby_likes$screen_name)
data_orderby_likes$account_integer <- as.numeric(data_orderby_likes$screen_name_factored)

# create a data frame to hold the output
data_accounts_likes <- data.frame()

num_accounts <- max(data_orderby_likes$account_integer)

for (i in 1:num_accounts) {
  # get the subset of tweets for this account
  account <- subset(data_orderby_likes, account_integer == i)
  
  # store the account's screen name for later
  screen_name <- as.character(account[1, "screen_name"])
  
  # get the vector of likes for the current account
  favorite_counts <- account["favorite_count"]

  # calculate the h_index  
  h_index_likes <- h_index(favorite_counts)

  # tack it onto the likes data frame  
  newline <- cbind.data.frame(screen_name, h_index_likes)
  data_accounts_likes <- rbind.data.frame(data_accounts_likes, newline)
}

# match the screen_names in order of the h_index_likes
data_accounts_likes$screen_name <- reorder(data_accounts_likes$screen_name, data_accounts_likes$h_index_likes)

# order this, then select top 50
likes_orderby_hindex <- data_accounts_likes[with(data_accounts_likes, order(-h_index_likes)), ]

forPlot <- likes_orderby_hindex[1:50, ]

p <- ggplot(data = forPlot, aes(x = h_index_likes, y = screen_name))
p +
  theme_cowplot(font_family = "Avenir Next") +
  background_grid(major = "xy") +
  geom_point(shape = 0) +
  labs(x = "h-index (based on likes)",
       y = "Twitter Username",
       caption = "h-index: number of tweets (n) with at least (n) likes\ne.g. an h-index of 50 means that account had 50 tweets\nthat were liked 50 or more times (higher is better)",
       title = paste("50 Most Liked Twitter Accounts in", subject_title),
       subtitle = "Compiled by Adrian Logue (@AdrianLogue)"
  )
